### PR TITLE
Hardware transcode

### PR DESCRIPTION
**Pull request by thelamer**
We should have some documentation for Hardware transcoding support and add abc to the video group so they can access the hardware under /dev/dri.

### CODE REVIEW

**Comment by sparklyballs** [comment]
4 linting warnings aside
why can't users just add their local users to the host's video group ? 

that way they break it rather than us

**Comment by thelamer** [comment]
The container has no visibility into the hosts group assignments, it still references it's /etc/group to determine the group the user belongs to and spit back permission errors. 

When bind mounting the device to exactly simulate what a host level instance of Plex would look like user the pid runs as should be a member of the video group matching the GID the host has set. 

At a bare minimum we should be documenting a how to for using Hardware Transcoding with our container, even if this is not an accepted methodology. 

Also this still needs testing, I only performed a hello world on a single Debian system as it is all I had with QuickSync support.

**Comment by tobbenb** [comment]
I haven't looked at it yet, but there is a PR for matching the permissions for /dev/dri on tvheadend also [here](https://github.com/linuxserver/docker-tvheadend/pull/87)

**Comment by thelamer** [comment]
That might be a better method, actually reading the GID from the mounted volume if it is there. That logic does not take into account if the GID is taken by another group though. 
Then the user does not ever need to check or pass the GID we just handle it if it is a mounted device.

**Comment by groenator** [comment]
Hi, 
When is this PR going to be merged into master? I really would like to use HW instead of software on my qnap.

**Comment by thelamer** [comment]
@groenator we are combining some other technical debt along with HW transcoding on this branch https://github.com/linuxserver/docker-plex/tree/pipeline-hw , as for a timeframe we need to get some info from Plex regarding using a new endpoint and internal testing I cannot give you an accurate time frame, but as soon as all the related work is done.

**Comment by thelamer** [comment]
I am closing this PR as this logic has been improved on this branch and will undergo actual release testing here: https://github.com/linuxserver/docker-plex/blob/pipeline-hw/root/etc/cont-init.d/50-gid-video

**Pull request closed without merging**
