### PR TITLE
Make sure we expose the same ports as plex

### PR DESCRIPTION
**Pull request by Hellowlol**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by CHBMB** [comment]
Unfortunately we can't merge this, all our `README.md` files are generated automatically from the `readme-vars.yml` file.  So any PRs need to be made against that file.

https://github.com/linuxserver/docker-plex/blob/master/readme-vars.yml

**Comment by thelamer** [comment]
Please make these changes to all of the Dockerfiles: 
Dockerfile
Dockerfile.armhf
Dockerfile.aarch64

**Comment by thelamer** [comment]
@Hellowlol re-ping about modifications to this to get it accepted, you need to make the same changes to all Dockerfiles

**Comment by Hellowlol** [comment]
I didnt do anything else as someone on discord (i cant remember the name) said that the ports didnt matter as the docker was running as host.

**Pull request merged**
