### PR TITLE
rebase to focal advertise bionic tag

### LINKED ISSUE #244: Trouble getting HDR tone mapping working on intel IGP
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

## Expected Behavior

Expecting HW tonemapping via intel GPU on latest plex 1.2. Instead, I get this error/warning from Plex when transcoding HDR content and cpu usage is high - 400-450% on Intel i5-9400

```
beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
```

## Current Behavior

Plex (and other OpenCL related utils) are unable to see the intel GPU and OpenCL is not available

## Steps to Reproduce

This might be related to versions of packages between ubuntu 18.04 which this image currently uses and 20.04. I am able to get a successful `clinfo` response on 20.04 but not 18.04.

```console
$ docker run --rm -it  --device /dev/dri:/dev/dri ubuntu:18.04 /bin/bash -c 'apt update && apt-get -qy install clinfo beignet-opencl-icd && clinfo -l'

beignet-opencl-icd: no supported GPU found, this is probably the wrong opencl-icd package for this hardware
(If you have multiple ICDs installed and OpenCL works, you can ignore this message)
Platform #0: Intel Gen OCL Driver
```

```console
$ docker run --rm -it  --device /dev/dri:/dev/dri ubuntu:20.04 /bin/bash -c 'apt update && apt-get -qy install clinfo beignet-opencl-icd && clinfo -l'

Platform #0: Intel Gen OCL Driver
 `-- Device #0: Intel(R) UHD Graphics Coffee Lake Desktop GT2
```

## Environment
**OS:** ubuntu 20.04
**CPU architecture:** x86_64
**How docker service was installed:** from docker's apt repo

### PR DESCRIPTION
**Pull request by thelamer**
We need to really test this one make sure there are not any glaring breaks with base OSs. Even if so we will now offer a bionic tag to help those people with issues and accommodate a transition. 

closes #244

### CODE REVIEW

**Comment by aptalca** [comment]
I'll test when it builds

**Comment by aptalca** [comment]
Works fine here locally

**Review by aptalca — APPROVED** [review]

**Comment by aptalca** [comment]
Tested on unraid and bionic host, worked fine. HDR tone mapping seems to have worked with intel gpu on unraid (not sure how to confirm, but the colors didn't look washed out)

**Review by nemchik — APPROVED** [review]

**Comment by joemiller** [comment]
@aptalca If tautalli is running you can see if HW-accelerated tone-mapping is active during a transcode. Might also be possible in Plex's own activity dashboard but I haven't checked.

**Comment by aptalca** [comment]
@joemiller they both show hw transcode, but nothing specifically about tone mapping

**Comment by joemiller** [comment]
here's what i see in tautalli with the 18.04 based image that is doing software tone mapping:

image

and 20.04 with HW tone mapping:

image

**Comment by aptalca** [comment]
That just shows the second one is doing a hw transcode and the first is doing a sw transcode? Where does it show anything about tone mapping?

**Comment by joemiller** [comment]
I believe so. The video does look noticeably better than I recalled before tonemapping. I don't have an older pre-1.2 install of PMS to compare to at the moment though.

**Comment by jyggen** [comment]
I haven't tested with the image in this particular PR, but I can verify that it does indeed say `HDR --> SDR` even without tone mapping. Unchecking "Enable HDR tone mapping" under the transcoder settings will result in a more greyish picture - so the tone mapping is very much working when enabled.

**Pull request merged**
