### PR TITLE
add chowner function for the config folder

### PR DESCRIPTION
**Pull request by aptalca**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by aptalca** [comment]
Set it to 50 for now, but can increase it since plex can have hundreds of thousands of files in the config folder

**Comment by thelamer** [comment]
It is not recursive unless you specifically enable globster and use double wild **. 
There is some delay loading large arrays into memory in scenarios like that.

**Comment by aptalca** [comment]
Will need to test the recursive perm check and see how much of an impact it has on container init time

**Comment by aptalca** [comment]
takes a really long time to cache, closing for now

**Pull request closed without merging**
