### PR TITLE
adding relay delete script

### PR DESCRIPTION
**Pull request by dbotamous**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

### CODE REVIEW

**Comment by tobbenb** [comment]
Would be nice if you suppliled any info at all about why this is needed.

**Comment by james-d-elliott** [comment]
Looks like a hack to only allow direct connections by removing the Plex Relay service executable. 

https://support.plex.tv/articles/216766168-accessing-a-server-through-relay/
https://www.reddit.com/r/PleX/comments/52ttmt/how_to_disable_plex_relay/

**Comment by JAGFin1** [comment]
That is a specific requirement, and not something we are likely to have in our image by default.

**Comment by CHBMB** [comment]
I agree, there's no possibility this can be merged as that would enforce the change on everyone who uses the container.

**Comment by dbotamous** [comment]
Sorry. 
I'm trying to learn github. I was trying to keep my downstream fork up to date with this upstream version. I was trying to merge my norelay branch into my master branch. Not sure what I did. 
Sorry again.

**Pull request closed without merging**
