### PR TITLE
adding beignet dependency for HW tone mapping

### PR DESCRIPTION
**Pull request by andywong36**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [ ] I have read the [contributing](https://github.com/linuxserver/docker-plex/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Adds HW tone mapping support. Tested on i5-7200u and HD 620 graphics

## Benefits of this PR and context:

Tackles #325 

## How Has This Been Tested?

Per the instructions in the [contributing guidelines](https://github.com/linuxserver/docker-plex/blob/383b7fb4617e0e377f3516266fabf73160490df5/.github/CONTRIBUTING.md)

## Source / References:

https://github.com/linuxserver/docker-plex/issues/325#issuecomment-1250091225

### CODE REVIEW

**Comment by thespad** [comment]
Please run our Jenkins builder locally https://github.com/linuxserver/docker-jenkins-builder/#running-against-local-project against the repo folder and push the resulting changes to the branch.

It's not normally needed but due to unfortunate timing there's been a CI change that will prevent PR builds succeeding if you cloned the master branch before it had completed a post-change build.

**Comment by aptalca** [comment]
Thanks for the PR, but I'd rather not play whack-a-mole with opencl packages anymore. For the last few months we bounced around from package version to package version, each update breaking it for a different set of gpus. We are now using the upstream recommended packages with the versions pinned and we'll follow their direction.

Plex needs to figure this out first and then it will work in our image.

Emby figured it out and it just works.

**Comment by aptalca** [comment]
Until then, if this added package works for you, you can use this mod to install it: https://github.com/linuxserver/docker-mods/tree/universal-package-install

**Comment by andywong36** [comment]
Thank you for the context! 

Closing this PR.

**Pull request closed without merging**
